### PR TITLE
Add android studio gradle project

### PR DESCRIPTION
**Pull request by halx99**

### CODE REVIEW

**Comment by sgowen** [comment]
Hmmm, so this was never merged? I'd like to use OpenAL-soft on Android if possible.

**Comment by halx99** [comment]
it's only for bug reproduce

**Comment by sgowen** [comment]
Ah I see. I got excited. An example Android Studio project demonstrating building and running openal-soft would be sweet.

**Comment by kcat** [comment]
OpenAL Soft is a library for playing 3D audio. The library itself doesn't run, it needs to be added to an app/game. There are a few example programs it comes with, but they're very simple general programs, which are built as part of the CMake project. The library would be added to an existing project, so it having its own project probably wouldn't be useful. But either way, OpenAL Soft is a rather standard CMake project, so you can use it the same way you'd use a CMake project on Android.

**Pull request closed without merging**
