### PR TITLE
Android build porting(use toolchain).

### PR DESCRIPTION
**Pull request by i25ffz**
Standalone Toolchain
====================

Make standalone android ndk toolchain($NDK/docs/STANDALONE-TOOLCHAIN.html):
$cd $NDK_ROOT
$./build/tools/make-standalone-toolchain.sh --platform=android-14 --install-dir=~/toolchains/arm-linux-androideabi-r9d-14
$export PATH=$PATH:~/toolchains/arm-linux-androideabi-r9d-14/bin

Source Install
====================

$cd build
$cmake -D CMAKE_TOOLCHAIN_FILE=../cmake/android.toolchain.cmake -G "Unix Makefiles" ..
$make -j4

### CODE REVIEW

**Comment by kcat** [comment]
OpenAL Soft contains an cross-compile toolchain for Android, so I'm closing this. If something's still missing, please let me know.

**Comment by i25ffz** [comment]
After testing, XCompile.txt be fine when use linux, buf got error when use cygwin. But my script is compatible both linux and cygwin.

**Comment by fatalfeel** [comment]
//for android build on ubuntu 14.04 64 bits

/opt/android-ndk-r8e/build/tools/make-standalone-toolchain.sh --system=linux-x86_64 --platform=android-14 --install-dir=/opt/android-ndk-r8e/standalone
export PATH=$PATH:/opt/android-ndk-r8e/standalone/bin

extract openal-soft-openal-soft-1.17.2.tar.gz

cd /root/openal-soft-openal-soft-1.17.2
gedit ./XCompile-Android.txt
SET(CMAKE_FIND_ROOT_PATH "SET THIS TO THE NDK TOOLCHAIN'S INSTALL PATH")
to
SET(CMAKE_FIND_ROOT_PATH /opt/android-ndk-r8e/standalone)

mkdir build
cd build
cmake .. -DCMAKE_TOOLCHAIN_FILE=../XCompile-Android.txt -DHOST=arm-linux-androideabi
make

**Comment by fatalfeel** [comment]
my android example and use openal by Jesse Stone
http://www.mediafire.com/download/u9fllfvneg235x1/openal-soft-master_android.tar.gz

**Pull request closed without merging**
