### PR TITLE
Fix check_include_file return unexpected result

### PR DESCRIPTION
**Pull request by halx99**
This patch will fix to avoid cause check_include_file return unexpected result

- build tools: Gradle -> cmake -> Ninja
- build target: android x86
- Reproduce step action: https://github.com/halx99/openal-soft/actions/runs/834150596
- Fixed action: https://github.com/halx99/openal-soft/actions/runs/834168309

### CODE REVIEW

**Comment by kcat** [comment]
This doesn't really explain what the problem is, and how it fixes it. What's the "unexpected result" from `check_file_include`, and what causes it? Newer CMake isn't supposed to need a toochain for iOS, so why is there one again? If the error is with Android, why is iOS code being changed/added?

**Comment by halx99** [comment]
Yes, maybe check ios only better

**Comment by halx99** [comment]
See follow cmake log, for android x86 the sse header files should be found, but check it failed and check neon header succeed.
```
/home/runner/work/openal-soft/openal-soft/hello-jni/app/src/main/cpp/CMakeLists.txt : C/C++ release|x86 : Performing Test HAVE_MSSE2_SWITCH
/home/runner/work/openal-soft/openal-soft/hello-jni/app/src/main/cpp/CMakeLists.txt : C/C++ release|x86 : {"cookie":"","inReplyTo":"configure","progressCurrent":509,"progressMaximum":1000,"progressMessage":"Configuring","progressMinimum":0,"type":"progress"}

/home/runner/work/openal-soft/openal-soft/hello-jni/app/src/main/cpp/CMakeLists.txt : C/C++ release|x86 : {"cookie":"","inReplyTo":"configure","message":"Performing Test HAVE_MSSE2_SWITCH - Failed","type":"message"}

/home/runner/work/openal-soft/openal-soft/hello-jni/app/src/main/cpp/CMakeLists.txt : C/C++ release|x86 : Performing Test HAVE_MSSE2_SWITCH - Failed
/home/runner/work/openal-soft/openal-soft/hello-jni/app/src/main/cpp/CMakeLists.txt : C/C++ release|x86 : {"cookie":"","inReplyTo":"configure","message":"Looking for xmmintrin.h","type":"message"}

/home/runner/work/openal-soft/openal-soft/hello-jni/app/src/main/cpp/CMakeLists.txt : C/C++ release|x86 : Looking for xmmintrin.h
/home/runner/work/openal-soft/openal-soft/hello-jni/app/src/main/cpp/CMakeLists.txt : C/C++ release|x86 : {"cookie":"","inReplyTo":"configure","progressCurrent":525,"progressMaximum":1000,"progressMessage":"Configuring","progressMinimum":0,"type":"progress"}

/home/runner/work/openal-soft/openal-soft/hello-jni/app/src/main/cpp/CMakeLists.txt : C/C++ release|x86 : {"cookie":"","inReplyTo":"configure","message":"Looking for xmmintrin.h - not found","type":"message"}

/home/runner/work/openal-soft/openal-soft/hello-jni/app/src/main/cpp/CMakeLists.txt : C/C++ release|x86 : Looking for xmmintrin.h - not found
/home/runner/work/openal-soft/openal-soft/hello-jni/app/src/main/cpp/CMakeLists.txt : C/C++ release|x86 : {"cookie":"","inReplyTo":"configure","message":"Looking for emmintrin.h","type":"message"}

/home/runner/work/openal-soft/openal-soft/hello-jni/app/src/main/cpp/CMakeLists.txt : C/C++ release|x86 : Looking for emmintrin.h
/home/runner/work/openal-soft/openal-soft/hello-jni/app/src/main/cpp/CMakeLists.txt : C/C++ release|x86 : {"cookie":"","inReplyTo":"configure","progressCurrent":541,"progressMaximum":1000,"progressMessage":"Configuring","progressMinimum":0,"type":"progress"}

/home/runner/work/openal-soft/openal-soft/hello-jni/app/src/main/cpp/CMakeLists.txt : C/C++ release|x86 : {"cookie":"","inReplyTo":"configure","message":"Looking for emmintrin.h - not found","type":"message"}

/home/runner/work/openal-soft/openal-soft/hello-jni/app/src/main/cpp/CMakeLists.txt : C/C++ release|x86 : Looking for emmintrin.h - not found
/home/runner/work/openal-soft/openal-soft/hello-jni/app/src/main/cpp/CMakeLists.txt : C/C++ release|x86 : {"cookie":"","inReplyTo":"configure","message":"Looking for pmmintrin.h","type":"message"}

/home/runner/work/openal-soft/openal-soft/hello-jni/app/src/main/cpp/CMakeLists.txt : C/C++ release|x86 : Looking for pmmintrin.h
/home/runner/work/openal-soft/openal-soft/hello-jni/app/src/main/cpp/CMakeLists.txt : C/C++ release|x86 : {"cookie":"","inReplyTo":"configure","progressCurrent":556,"progressMaximum":1000,"progressMessage":"Configuring","progressMinimum":0,"type":"progress"}

/home/runner/work/openal-soft/openal-soft/hello-jni/app/src/main/cpp/CMakeLists.txt : C/C++ release|x86 : {"cookie":"","inReplyTo":"configure","message":"Looking for pmmintrin.h - not found","type":"message"}

/home/runner/work/openal-soft/openal-soft/hello-jni/app/src/main/cpp/CMakeLists.txt : C/C++ release|x86 : Looking for pmmintrin.h - not found
/home/runner/work/openal-soft/openal-soft/hello-jni/app/src/main/cpp/CMakeLists.txt : C/C++ release|x86 : {"cookie":"","inReplyTo":"configure","message":"Looking for smmintrin.h","type":"message"}

/home/runner/work/openal-soft/openal-soft/hello-jni/app/src/main/cpp/CMakeLists.txt : C/C++ release|x86 : Looking for smmintrin.h
/home/runner/work/openal-soft/openal-soft/hello-jni/app/src/main/cpp/CMakeLists.txt : C/C++ release|x86 : {"cookie":"","inReplyTo":"configure","progressCurrent":571,"progressMaximum":1000,"progressMessage":"Configuring","progressMinimum":0,"type":"progress"}

/home/runner/work/openal-soft/openal-soft/hello-jni/app/src/main/cpp/CMakeLists.txt : C/C++ release|x86 : {"cookie":"","inReplyTo":"configure","message":"Looking for smmintrin.h - not found","type":"message"}

/home/runner/work/openal-soft/openal-soft/hello-jni/app/src/main/cpp/CMakeLists.txt : C/C++ release|x86 : Looking for smmintrin.h - not found
/home/runner/work/openal-soft/openal-soft/hello-jni/app/src/main/cpp/CMakeLists.txt : C/C++ release|x86 : {"cookie":"","inReplyTo":"configure","message":"Looking for arm_neon.h","type":"message"}

/home/runner/work/openal-soft/openal-soft/hello-jni/app/src/main/cpp/CMakeLists.txt : C/C++ release|x86 : Looking for arm_neon.h
/home/runner/work/openal-soft/openal-soft/hello-jni/app/src/main/cpp/CMakeLists.txt : C/C++ release|x86 : {"cookie":"","inReplyTo":"configure","progressCurrent":585,"progressMaximum":1000,"progressMessage":"Configuring","progressMinimum":0,"type":"progress"}

/home/runner/work/openal-soft/openal-soft/hello-jni/app/src/main/cpp/CMakeLists.txt : C/C++ release|x86 : {"cookie":"","inReplyTo":"configure","message":"Looking for arm_neon.h - found","type":"message"}

/home/runner/work/openal-soft/openal-soft/hello-jni/app/src/main/cpp/CMakeLists.txt : C/C++ release|x86 : Looking for arm_neon.h - found
/home/runner/work/openal-soft/openal-soft/hello-jni/app/src/main/cpp/CMakeLists.txt : C/C++ release|x86 : {"cookie":"","inReplyTo":"configure","message":"CMake Error at ../../../../../CMakeLists.txt:384 (message):\n  Failed to enabled required SSE CPU extensions\n\n","title":"Error","type":"message"}
```

**Comment by kcat** [comment]
```
/home/runner/work/openal-soft/openal-soft/hello-jni/app/src/main/cpp/CMakeLists.txt : C/C++ release|x86 : Looking for xmmintrin.h
/home/runner/work/openal-soft/openal-soft/hello-jni/app/src/main/cpp/CMakeLists.txt : C/C++ release|x86 : {"cookie":"","inReplyTo":"configure","progressCurrent":525,"progressMaximum":1000,"progressMessage":"Configuring","progressMinimum":0,"type":"progress"}

/home/runner/work/openal-soft/openal-soft/hello-jni/app/src/main/cpp/CMakeLists.txt : C/C++ release|x86 : {"cookie":"","inReplyTo":"configure","message":"Looking for xmmintrin.h - not found","type":"message"}
```

That doesn't show why it's not found, or why the proposed change fixes it. It also apparently fails the `-msse2` check. Can you provide the CMakeError.log?

**Comment by halx99** [comment]
Well, the full log actually present on github action page: https://github.com/halx99/openal-soft/actions/runs/834150596

**Comment by halx99** [comment]
I think the root cause is the cmake default variable `CMAKE_TRY_COMPILE_PLATFORM_VARIABLES` was overridden by follow platform-uncheck code:
```cmake
set(CMAKE_TRY_COMPILE_PLATFORM_VARIABLES
    "CMAKE_XCODE_ATTRIBUTE_CODE_SIGNING_REQUIRED"
    "CMAKE_XCODE_ATTRIBUTE_CODE_SIGNING_ALLOWED")
```

**Comment by halx99** [comment]
[CMakeError.log](https://github.com/kcat/openal-soft/files/6470316/CMakeError.log)

**Comment by kcat** [comment]
Then does simply changing it to
```cmake
set(CMAKE_TRY_COMPILE_PLATFORM_VARIABLES
    ${CMAKE_TRY_COMPILE_PLATFORM_VARIABLES}
    "CMAKE_XCODE_ATTRIBUTE_CODE_SIGNING_REQUIRED"
    "CMAKE_XCODE_ATTRIBUTE_CODE_SIGNING_ALLOWED")
```
work, without hiding it behind an iOS check?

**Comment by halx99** [comment]
> Then does simply changing it to
> 
> ```cmake
> set(CMAKE_TRY_COMPILE_PLATFORM_VARIABLES
>     ${CMAKE_TRY_COMPILE_PLATFORM_VARIABLES}
>     "CMAKE_XCODE_ATTRIBUTE_CODE_SIGNING_REQUIRED"
>     "CMAKE_XCODE_ATTRIBUTE_CODE_SIGNING_ALLOWED")
> ```
> 
> work, without hiding it behind an iOS check?

Yep, it's also works

**Comment by halx99** [comment]
But it's xcode attribute, maybe with `CMAKE_SYSTEM_NAME` check is better?

**Comment by kcat** [comment]
Can XCode be used on non-iOS systems/targets where it could pose a problem?

**Comment by halx99** [comment]
> Can XCode be used on non-iOS systems/targets where it could pose a problem?

If build target is `macOS`, the woraround cmake settings isn't required

**Comment by halx99** [comment]
or check apple is better?
```
if(APPLE)
  set(CMAKE_TRY_COMPILE_PLATFORM_VARIABLES
      ${CMAKE_TRY_COMPILE_PLATFORM_VARIABLES}
      "CMAKE_XCODE_ATTRIBUTE_CODE_SIGNING_REQUIRED"
      "CMAKE_XCODE_ATTRIBUTE_CODE_SIGNING_ALLOWED")
endif()
```

**Comment by halx99** [comment]
Sorry, there are tvOS, watchOS, and I have checked your c++ source code, not process them, and I modified the c++ code same with iOS target, seems could be compile success.

**Comment by halx99** [comment]
Notes: AudioUnit not supported by watchOS, see:  https://developer.apple.com/documentation/audiotoolbox/audiounit, but at least, move `CMAKE_TRY_COMPILE_PLATFORM_VARIABLES` to external with `APPLE` checking could support tvOS

**Pull request merged**
