### PR TITLE
Build NEON code with -mfpu=neon

### PR DESCRIPTION
**Pull request by tpetazzoni**
The ARM-specific NEON code needs to be built with -mfpu=neon to avoid
build failures when a difference FPU is used by default by the
compiler.

Fixes issue #54.

Signed-off-by: Thomas Petazzoni <thomas.petazzoni@free-electrons.com>

### CODE REVIEW

**Comment by kcat** [comment]
Are there any potential ABI issues by building one source file with ```-mfpu=neon``` and others without? That is, would sources compiled with that switch expect float parameters to be passed differently, or expect the FPU to be in a certain kind of state, compared to sources compiled without that switch?

**Comment by tpetazzoni** [comment]
@kcat I don't *think* there are ABI issues. The floating point ABI is defined by -mfloat-abi (soft, softfp, hard), and the floating point ABI is what defines how floating point arguments are passed between functions. And the linker anyway doesn't allow you to link -mfloat-abi=softfp code with -mfloat-abi=hard code. So I *think* building just one file with -mfpu=neon is correct (of course, assuming the HW actually has NEON support), but I am not a definitive expert on the topic.

**Comment by kcat** [comment]
You have tested it, at least? Made sure the NEON mixers work with this?

**Comment by tpetazzoni** [comment]
@kcat No, I only did build testing. I'm not using OpenAL, I'm just submitting this because we're facing build issues in Buildroot. I've asked the people using OpenAL in Buildroot to test the patch, we'll see what they say.

**Comment by kcat** [comment]
I think I may need to do runtime detection for NEON too, otherwise a lib built with NEON support will crash if run on a device without it (rather than falling back to the C methods). Or simply leave NEON off by default, but then devices that have NEON won't take advantage of it.

**Comment by tpetazzoni** [comment]
VLC relies on /proc/cpuinfo, see http://git.videolan.org/?p=vlc.git;a=blob;f=src/linux/cpu.c;h=38fcce98f8526f2b0dba7bbfd64a36f7e3ecefeb;hb=HEAD#l45

**Pull request merged**
