### PR TITLE
Enable and enforce dependencies on CI services.

### PR DESCRIPTION
**Pull request by adrianbroher**
This PR is a work in progress

This PR (should) contain commits to allow that more parts of the project like backends or example programs are build and enforced to build to check for regressions in the build system.  Due to the nature of the CI services in question I can only test changes as external contributor by pushing to to this PR.  I will notify you when I consider the changes good enough for a review.

### CODE REVIEW

**Comment by adrianbroher** [comment]
After some tuning the CI now builds all backends.

**Comment by kcat** [comment]
So this is now ready for merge, then?

**Comment by adrianbroher** [comment]
> So this is now ready for merge, then?

Yes, unless you have questions or remarks to the PR itself.

**Comment by kcat** [comment]
Only thing I notice is that the Android build doesn't build with NEON support. The ```-mfpu=neon``` check passes, but it seems to not find ```arm_neon.h```. It's not too big of a deal, but do you know why that might be?

**Comment by adrianbroher** [comment]
> Only thing I notice is that the Android build doesn't build with NEON support.

I'm not well versed with embedded hardware, but the NDK toolchain files seems to select the `armeabi-v7a` without NEON support if you don't add any specific CMake parameters.  Maybe the cross compiler always supports `-mfpu=neon` and therefor is not a reliable check.

https://android.googlesource.com/platform/ndk/+/master/build/cmake/android.toolchain.cmake

**Pull request merged**
